### ISSUE TITLE
More details about privacy

### ISSUE THREAD

**Issue by huyz** [neufeldtech/secretmessage-go#2]
I have several questions about privacy.

1. It's not clear from the README whether Slack ever gets to see the secret content.  Is it only the client that displays it but the server never gets a copy?  Maybe you can get into the details of how encryption is used.
2. Can this be used in public channels?  Can multiple users see the secret message?  Can the same viewer see the message more than once?  What exactly happens after the Delete button is pressed.
3. Can the messages be automatically destroyed after a certain amount of time?  If not, how hard do you think it would be to contribute code to add that feature?

**Comment by neufeldtech** [comment]
Hey @huyz, please find below answers in-line
> I have several questions about privacy.
> 
> 1. It's not clear from the README whether Slack ever gets to see the secret content.  Is it only the client that displays it but the server never gets a copy?  Maybe you can get into the details of how encryption is used.

When a user sends a message with `/secret my message` the message payload is sent to Slack's servers (just as all messages are) through Slack's encrypted Websocket connection. Slack's server then forwards the payload via webhook (Over encrypted TLS) to the hosted secretmessage-go application. Once we have the payload on the secretmessage-go server, we encrypt the payload using the ID of the message as the encryption key. Once encrypted, the code performs a one-way hash of the secret ID and stores the secret in a redis store with the key being `<hashed secret ID>` and the value `<encrypted payload of secret>`. In this way, the only one who can decrypt the message stored in the redis payload is the person that knows the secret ID of the message, which is the user that clicks on the`Read Message` button.

The raw message payload will be passing through Slack's infrastructure, but in theory, it's not _stored_ in the same way that regular slack messages are in their MySQL databases - I.e. One cannot search slack later to find sensitive content that was passed from user to user with the application.

> 2. Can this be used in public channels?  Can multiple users see the secret message?  Can the same viewer see the message more than once?  What exactly happens after the Delete button is pressed.

Yes, this can be used in public channels, but the application of this may not make practical sense. In a public channel setting, everyone in the channel will see `huyz sent a secret message` and anyone will be able to click on the `Read Message` button. The first person that clicks on the `Read message` button will be the only one that can see the content. When they click this button, the secret is given to them via a Slack _ephemeral message_ (where it says `Only Visible to you`). Using ephemeral messages as the delivery medium, we get our desired effect of having the sensitive message only available for a short time - until the user reloads their Slack client or presses the delete button.

When messages are read by clicking the delete button, they are delivered to the user (by way of ephemeral message - see above) and we remove the secret from the Redis datastore. The delete button is just a convenience button so that the reader of said message can remove it from the screen easily without reloading their slack client, or manually deleting the message.

> 3. Can the messages be automatically destroyed after a certain amount of time?  If not, how hard do you think it would be to contribute code to add that feature?

There are two behaviours here that you could be referencing, and I'll comment on both, but neither are implemented at this time.

1) Can `an unread` (unclaimed) message be automatically destroyed after a period of time?
We could certainly remove the key from Redis based on a TTL, but there are other open questions on if we should (or if it's even technically possible to) provide further feedback to the Slack client to remove the message from the channel because the secret is no longer there. If we just blindly implemented a TTL and a message was attempted to be retrieved after expiry, the user would receive the error message `secret not found` or similar.

2) Can `a read` (claimed) message be automatically destroyed after a period of time without me having to click `delete message` or reload my Slack client?
I'd have to do more research with the Slack API to see if this is possible, but there'd need to be a larger discussion on if this is something that we'd want to implement. In many cases, users sharing sensitive data need some time to digest or move the sensitive message to a more appropriate location (i.e. their password store) after receiving a message. If we force them to act quickly by having a timer, they might be encouraged to copy/paste their sensitive secret back into their personal Slack channel (or other notepad or insecure medium), essentially negating the 'ephemeral' nature of the message by making it permanent somewhere else.

**Comment by neufeldtech** [comment]
Closing this up for now. Let me know if there are any further questions
