### ISSUE TITLE
not working on self-hosted deploy

### ISSUE THREAD

**Issue by lucmichalski** [neufeldtech/secretmessage-go#9]
Hi @neufeldtech 

Hope you are doing all well !

I dockerized and deployed secretmessage-go for testing it but I have an error without any logs about what is going wrong.

When i trigger (succesfully) the "/secret" command with a message I get a reply to read a message but I cannot open it. Do you know what could be the reason ?

Can you provide more details about the slack app setup with the api endpoints from **secretmessage-go**

My logs:
```sh
secrets                     | [GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.
secrets                     | 
secrets                     | [GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
secrets                     |  - using env:	export GIN_MODE=release
secrets                     |  - using code:	gin.SetMode(gin.ReleaseMode)
secrets                     | 
secrets                     | [GIN-debug] GET    /secrets/health           --> github.com/neufeldtech/secretmessage-go/pkg/secretmessage.(*PublicController).HandleHealth-fm (4 handlers)
secrets                     | [GIN-debug] GET    /secrets/auth/slack       --> github.com/neufeldtech/secretmessage-go/pkg/secretmessage.(*PublicController).HandleOauthBegin-fm (4 handlers)
secrets                     | [GIN-debug] GET    /secrets/auth/slack/callback --> github.com/neufeldtech/secretmessage-go/pkg/secretmessage.(*PublicController).HandleOauthCallback-fm (4 handlers)
secrets                     | [GIN-debug] POST   /secrets/slash            --> github.com/neufeldtech/secretmessage-go/pkg/secretmessage.(*PublicController).HandleSlash-fm (5 handlers)
secrets                     | [GIN-debug] POST   /secrets/interactive      --> github.com/neufeldtech/secretmessage-go/pkg/secretmessage.(*PublicController).HandleInteractive-fm (5 handlers)
secrets                     | [GIN-debug] Listening and serving HTTP on 0.0.0.0:8080
secrets                     | time="2021-06-06T17:01:35Z" level=info msg="Booted and listening on port 8080" source="main.go:107"
secrets                     | [GIN] 2021/06/06 - 17:01:45 | 200 |  192.265903ms |    xx.xx.xx.xx | POST     /secrets/slash
secrets                     | [GIN] 2021/06/06 - 17:06:15 | 200 |  166.082294ms |    xx.xx.xx.xx | POST     /secrets/slash
secrets                     | [GIN] 2021/06/06 - 17:06:35 | 200 |     321.697µs |      xx.xx.xx.xx | GET      /secrets/health
secrets                     | [GIN] 2021/06/06 - 17:07:06 | 200 |  138.289811ms |    xx.xx.xx.xx | POST     /secrets/slash
secrets                     | [GIN] 2021/06/06 - 17:08:26 | 500 |     519.613µs |    xx.xx.xx.xx | POST     /secrets/interactive
secrets                     | [GIN] 2021/06/06 - 17:11:35 | 200 |     548.608µs |      xx.xx.xx.xx | GET      /secrets/health
secrets                     | [GIN] 2021/06/06 - 17:16:35 | 200 |     542.527µs |      xx.xx.xx.xx| GET      /secrets/health
```

Thanks for any insights or inputs on that issue.

Cheers,
Luc Michalski

**Comment by neufeldtech** [comment]
Hey @lucmichalski,

I see that your router is listening on the endpoints `/secrets/<path>` instead of just `/<path>` and this is the first place you should investigate. What config did you change (or what environment variables did you use) to cause the app to listen at these paths? In my deployment, I have the router listening at the root, like this:

```bash
$ go run .
[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /health                   --> github.com/neufeldtech/secretmessage-go/pkg/secretmessage.(*PublicController).HandleHealth-fm (4 handlers)
[GIN-debug] GET    /auth/slack               --> github.com/neufeldtech/secretmessage-go/pkg/secretmessage.(*PublicController).HandleOauthBegin-fm (4 handlers)
[GIN-debug] GET    /auth/slack/callback      --> github.com/neufeldtech/secretmessage-go/pkg/secretmessage.(*PublicController).HandleOauthCallback-fm (4 handlers)
[GIN-debug] POST   /slash                    --> github.com/neufeldtech/secretmessage-go/pkg/secretmessage.(*PublicController).HandleSlash-fm (5 handlers)
[GIN-debug] POST   /interactive              --> github.com/neufeldtech/secretmessage-go/pkg/secretmessage.(*PublicController).HandleInteractive-fm (5 handlers)
INFO[0000] Booted and listening on port 8080             source="main.go:107"
[GIN-debug] Listening and serving HTTP on 0.0.0.0:8080
```
See some notes on the required Slack setup below:

# Slack App Web Interface Config

## Add a Slash Command
- Create a slash command for `/secret`
- Configure it to POST to https://yoursite.example.com/slash
![image](https://user-images.githubusercontent.com/8252744/120935025-77c2a000-c6c6-11eb-8d2f-90e601f84ce7.png)

## Enable Interactivity & Shortcuts
- Set interactivity URL to https://yoursite.example.com/interactive
![image](https://user-images.githubusercontent.com/8252744/120935073-ab052f00-c6c6-11eb-8ae1-0f266cbc96d5.png)

## Oauth and Permissions
- Set Redirect URL to https://yoursite.example.com/auth/slack/callback
- Add Bot Token Scopes
   -  chat:write
   - commands
   - workflow.steps.execute (not used, but present for future development)

![image](https://user-images.githubusercontent.com/8252744/120935386-24515180-c6c8-11eb-8079-93f4987340c3.png)


## App Credentials
- Note the Client ID, Client Secret, and Signing Secret. You'll need these later

# Environment variables
- Setup the following environment variables
- `SLACK_SIGNING_SECRET="<set to slack signing secret>"`
- `SLACK_CLIENT_ID="<set to slack client id for oauth>"`
- `SLACK_CLIENT_SECRET="<set to slack client secret for oauth>"`
- `SLACK_CALLBACK_URL="https://<yoursite.example.com/auth/slack/callback"`
- `APP_URL="https://<yoursite.example.com>"`
- `DATABASE_URL="postgres://username:password@1.2.3.4:5432/your_database_name?sslmode=disable"`

**Comment by lucmichalski** [comment]
Thanks for this quick and detailed reply :-)

<img width="285" alt="Screenshot 2021-06-07 at 07 03 16" src="https://user-images.githubusercontent.com/1963546/120961995-287c7e00-c75f-11eb-8974-ac254c99831e.png">

I fixed the prefix path you mentioned but it sounds like message attachement are disabled, the button is not working ^^

**Comment by lucmichalski** [comment]
all is working, I have some feedbacks if you are interested. :-)

**Comment by neufeldtech** [comment]
Glad to hear you got it working.
